#ifndef GLOBAL_H
#define GLOBAL_H

#define OCL_PLATFORM 0
#define OCL_DEVICE 0

#define NUM_EXAMPLES 2048
#define NUM_FEATURES 8
#define NUM_WORK_ITEMS 256
#define NUM_ITERATIONS 50000
#define LEARNING_RATE 0.1f/NUM_EXAMPLES

#endif
